services:
  db:
    build: ./db
    ports:
      - "5432:5432"
  web:
    build: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - api
  api:
    build: ./Backend
    ports:
      - "8000:8000"
    depends_on:
      - db